package com.java.project.ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hemasreekoganti
 */
public class HomePage extends javax.swing.JFrame {
    String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Hospital_Database;integratedSecurity=true;";

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        txt_search.setVisible(false);
        lbl_fname.setVisible(false);
        lbl_lname.setVisible(false);
        lbl_roomcost.setVisible(false);
        lbl_testcost.setVisible(false);
        lbl_total.setVisible(false);
        txt_fname.setVisible(false);
        txt_lname.setVisible(false);
        txt_roomcost.setVisible(false);
        txt_testcost.setVisible(false);
        txt_total.setVisible(false);
        btn_search.setVisible(false);
        btn_patientdetails.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        lbl_welcome = new javax.swing.JLabel();
        btn_inpatient = new javax.swing.JButton();
        btn_output = new javax.swing.JButton();
        lbl_fname = new javax.swing.JLabel();
        lbl_lname = new javax.swing.JLabel();
        lbl_roomcost = new javax.swing.JLabel();
        lbl_testcost = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        txt_roomcost = new javax.swing.JTextField();
        txt_testcost = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        txt_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        btn_patientdetails = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_welcome.setText("                             WELCOME!!!!");

        btn_inpatient.setText("IN PATIENT");
        btn_inpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inpatientActionPerformed(evt);
            }
        });

        btn_output.setText("OUT PATIENT");
        btn_output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_outputActionPerformed(evt);
            }
        });

        lbl_fname.setText("FirstName :");

        lbl_lname.setText("LastName :");

        lbl_roomcost.setText("Room cost:");

        lbl_testcost.setText("Test Cost :");

        lbl_total.setText("Total :");

        txt_testcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_testcostActionPerformed(evt);
            }
        });

        txt_search.setText("Enter Patient ID to search");
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });

        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        btn_patientdetails.setText("PatientDetails");
        btn_patientdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_patientdetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(lbl_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_lname)
                                    .addComponent(lbl_roomcost)
                                    .addComponent(lbl_testcost)
                                    .addComponent(lbl_total))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_lname)
                                    .addComponent(txt_roomcost)
                                    .addComponent(txt_testcost)
                                    .addComponent(txt_total, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_fname)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(1, 1, 1)
                        .addComponent(btn_search)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btn_inpatient)
                .addGap(31, 31, 31)
                .addComponent(btn_output)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_patientdetails)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lbl_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_inpatient)
                    .addComponent(btn_output)
                    .addComponent(btn_patientdetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fname)
                    .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_lname)
                    .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_roomcost)
                    .addComponent(txt_roomcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_testcost)
                    .addComponent(txt_testcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_total)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inpatientActionPerformed
        try {
            // TODO add your handling code here:
            PatientClass p=new PatientClass();
            p.setVisible(true);
            } 
        catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_inpatientActionPerformed

    private void btn_outputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_outputActionPerformed
        // TODO add your handling code here:
       txt_search.setVisible(true);
       btn_search.setVisible(true);
        
    }//GEN-LAST:event_btn_outputActionPerformed

    private void txt_testcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_testcostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_testcostActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_searchActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
                if(txt_search.getText() != null || txt_search.getText()=="")
        {
            
        
         lbl_fname.setVisible(true);
        lbl_lname.setVisible(true);
        lbl_roomcost.setVisible(true);
        lbl_testcost.setVisible(true);
        lbl_total.setVisible(true);
        txt_fname.setVisible(true);
        txt_lname.setVisible(true);
        txt_roomcost.setVisible(true);
        txt_testcost.setVisible(true);
        txt_total.setVisible(true);
        String pid=txt_search.getText();
        Connection con; 
            try {
                con = DriverManager.getConnection(connectionUrl);
                
        Statement stmt = con.createStatement();
        PreparedStatement ps=null;
        PreparedStatement pinsert=null;
        PreparedStatement pselect=null;
        String SQL1="SELECT fname,lname FROM patient WHERE pid=?";
        ps = con.prepareStatement(SQL1);
        ps.setString(1, pid);
        ResultSet rs = ps.executeQuery();
       while (rs.next()) {
              System.out.println( rs.getString("fname"));
              txt_fname.setText(rs.getString("fname"));
              txt_lname.setText(rs.getString("lname"));
              txt_roomcost.setText("500");
              txt_testcost.setText("1200");
              txt_total.setText("1700");
              //deptid=rs.getInt("lname");
              //System.out.println();
       }
       } 
            catch (SQLException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
                      }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Enter patient id for details");
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_patientdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_patientdetailsActionPerformed
        // TODO add your handling code here:
         TotalPatients tp=new TotalPatients();
         //tp.setVisible(true);
    }//GEN-LAST:event_btn_patientdetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inpatient;
    private javax.swing.JButton btn_output;
    private javax.swing.JButton btn_patientdetails;
    private javax.swing.JButton btn_search;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JLabel lbl_fname;
    private javax.swing.JLabel lbl_lname;
    private javax.swing.JLabel lbl_roomcost;
    private javax.swing.JLabel lbl_testcost;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_roomcost;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_testcost;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
