package com.java.project.ui;

import com.toedter.calendar.JDateChooser;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hemasreekoganti
 */
public class RegistrationForm extends javax.swing.JFrame {
    
    String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Hospital_Database;integratedSecurity=true;";
    int counter=1010;
    private JDateChooser date_chooser;
    private java.util.Date date;
    private Object JOptionpane;

    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm() {
        initComponents();
        groupButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_fname = new javax.swing.JLabel();
        lbl_mname = new javax.swing.JLabel();
        lbl_lname = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        txt_mname = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        lbl_username = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        lbl_password = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        lbl_gender = new javax.swing.JLabel();
        rbtn_male = new javax.swing.JRadioButton();
        rbtn_female = new javax.swing.JRadioButton();
        dateofjoin = new javax.swing.JLabel();
        lbl_emptype = new javax.swing.JLabel();
        rbtn_temporary = new javax.swing.JRadioButton();
        rbtn_permanent = new javax.swing.JRadioButton();
        lbl_hno = new javax.swing.JLabel();
        txt_hno = new javax.swing.JTextField();
        lbl_city = new javax.swing.JLabel();
        txt_city = new javax.swing.JTextField();
        lbl_state = new javax.swing.JLabel();
        txt_state = new javax.swing.JTextField();
        lbl_country = new javax.swing.JLabel();
        txt_country = new javax.swing.JTextField();
        btn_signup = new javax.swing.JButton();
        lbl_deptname = new javax.swing.JLabel();
        cb_deptname = new javax.swing.JComboBox();
        dc_doj = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_fname.setText("First Name :");

        lbl_mname.setText("Middle Name :");

        lbl_lname.setText("Last Name :");

        txt_mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mnameActionPerformed(evt);
            }
        });

        txt_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lnameActionPerformed(evt);
            }
        });

        lbl_username.setText("UserName :");

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });

        lbl_password.setText("Password :");

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });

        lbl_gender.setText("Gender :");

        rbtn_male.setText("Male");

        rbtn_female.setText("Female");

        dateofjoin.setText("Date Of Joining :");

        lbl_emptype.setText("Employee Type :");

        rbtn_temporary.setText("Temporary");

        rbtn_permanent.setText("Permanent");
        rbtn_permanent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_permanentActionPerformed(evt);
            }
        });

        lbl_hno.setText("HNO :");

        lbl_city.setText("City :");

        txt_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cityActionPerformed(evt);
            }
        });

        lbl_state.setText("State :");

        txt_state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stateActionPerformed(evt);
            }
        });

        lbl_country.setText("Country :");

        txt_country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_countryActionPerformed(evt);
            }
        });

        btn_signup.setText("SIGN  UP");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });

        lbl_deptname.setText("Department :");

        cb_deptname.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Allergy", "Nurse", "Cardiology", "Pathology", "Surgery", "Cleaner", "Accounts", "Security", "Radiology", "Anesthesia", " " }));
        cb_deptname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_deptnameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_state)
                            .addComponent(lbl_country))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btn_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_city)
                                    .addComponent(lbl_hno)
                                    .addComponent(lbl_emptype)
                                    .addComponent(lbl_gender))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_state, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_country, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_hno, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtn_temporary)
                                            .addComponent(rbtn_male))
                                        .addGap(58, 58, 58)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtn_female)
                                            .addComponent(rbtn_permanent))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(lbl_deptname)
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_username)
                                            .addComponent(lbl_password))
                                        .addGap(82, 82, 82)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_password)
                                            .addComponent(txt_username)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_mname)
                                            .addComponent(lbl_fname)
                                            .addComponent(lbl_lname))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_mname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                                            .addComponent(txt_fname, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_lname))))
                                .addGap(86, 86, 86)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(cb_deptname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(dateofjoin)
                                .addGap(55, 55, 55)
                                .addComponent(dc_doj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fname)
                    .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_mname)
                    .addComponent(txt_mname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_lname)
                    .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lbl_username)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_password)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_gender)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_emptype))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtn_male)
                            .addComponent(rbtn_female))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtn_temporary)
                            .addComponent(rbtn_permanent))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_hno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_hno))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_city)
                    .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_state)
                    .addComponent(txt_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_country, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btn_signup)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateofjoin)
                    .addComponent(dc_doj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(159, 159, 159)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_deptname)
                    .addComponent(cb_deptname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_countryActionPerformed

    private void txt_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lnameActionPerformed

    private void rbtn_permanentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_permanentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_permanentActionPerformed

    private void txt_mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mnameActionPerformed

    private void txt_stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stateActionPerformed

    private void txt_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cityActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        // TODO add your handling code here:
          try
          {
        counter++;
        String user=txt_username.getText();
        String pass=txt_password.getText();
        String fname=txt_fname.getText();
        String mname=txt_mname.getText();
        String lname=txt_lname.getText();
        String hno=txt_hno.getText();
        String city=txt_city.getText();
        String state=txt_state.getText();
        String country=txt_country.getText();
        String gender="";
        if(rbtn_male.isSelected())
         gender=rbtn_male.getText();
        if(rbtn_female.isSelected())
         gender=rbtn_female.getText();
        
        String emptype="";
        if(rbtn_temporary.isSelected())
         emptype=rbtn_temporary.getText();
        if(rbtn_permanent.isSelected())
         emptype=rbtn_permanent.getText();
        
        SimpleDateFormat dcn = new SimpleDateFormat("yyyy-MM-dd");
        String date1 = dcn.format(dc_doj.getDate() );
        Date dt=dcn.parse(date1);
        System.out.println(dcn.format(dt)); 
        //Date date2=new SimpleDateFormat("dd/MM/yyyy").parse(date1);
        LocalDate now = LocalDate.now();    
        String dname= (String)cb_deptname.getSelectedItem();
        int deptid=0;
       if((fname == null || fname.isEmpty()) || (lname == null || lname.isEmpty()) || (gender == null || gender.isEmpty()) || (emptype == null ||
               emptype.isEmpty()) || (pass == null || pass.isEmpty()) ||(date1==null))
       {
           //JFrame frame=new JFrame();
           JOptionPane.showMessageDialog(null,"THE FIELDS FIRSTNAME, LASTNAME,GENDER,EMAIL,GENDER,EMPLOYEE TYPE,PASSWORD CANNOT BE EMPTY");
           System.out.println("THE FIELDS FIRSTNAME, LASTNAME,GENDER,EMAIL,GENDER,EMPLOYEE TYPE,PASSWORD CANNOT BE EMPTY");
       }
       else
       {
        Connection con = DriverManager.getConnection(connectionUrl); 
        Statement stmt = con.createStatement();
        PreparedStatement ps=null;
        PreparedStatement pinsert=null;
        PreparedStatement pselect=null;
        String SQL1="SELECT deptid FROM dbo.Department WHERE dname=?";
        ps = con.prepareStatement(SQL1);
        ps.setString(1, dname);
        ResultSet rs = ps.executeQuery();
       while (rs.next()) {
              System.out.println( rs.getString("deptid"));
              deptid=rs.getInt("deptid");
              System.out.println(deptid);
       }
        String sel="SELECT max(empid) as empid from Employees";
        pselect =con.prepareStatement(sel);
        ResultSet result=pselect.executeQuery();
        while(result.next())
        {
            System.out.println( result.getString("empid"));
            counter=Integer.parseInt(result.getString("empid")) + 1;
            System.out.println(counter);
        }
        String SQL = "INSERT INTO Employees(empid,fname,mname,lname,gender,emptype,Hno,country,city,state,date_of_joining,email,deptid,password) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        pinsert=con.prepareStatement(SQL);
        pinsert.setInt(1,counter);
        pinsert.setString(2, fname);
        pinsert.setString(3, mname);
        pinsert.setString(4, lname);
        pinsert.setString(5, gender);
        pinsert.setString(6, emptype);
        pinsert.setString(7, hno);
        pinsert.setString(8, country);
        pinsert.setString(9, city);
        pinsert.setString(10, state);
        pinsert.setString(11, dcn.format(dt));
        pinsert.setString(12, user);
        pinsert.setInt(13, deptid);
        pinsert.setString(14, pass);
        //ResultSet rinsert=
        pinsert.executeUpdate();
        JOptionPane.showMessageDialog(null,"CREATED USER SUCCESSFULLY!");
         HomePage home=new HomePage();
         home.setVisible(true);
     } 
        
          }
          catch (SQLException e)
          {
            e.printStackTrace();
          } 
          catch (ParseException ex) 
          {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_btn_signupActionPerformed
    private void groupButton( )
    {
        ButtonGroup bg1 = new ButtonGroup( );
        bg1.add(rbtn_female);
        bg1.add(rbtn_male);
        bg1.clearSelection();
        ButtonGroup bg2=new ButtonGroup();
        bg2.add(rbtn_temporary);
        bg2.add(rbtn_permanent);
        bg2.clearSelection();
    }
    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void cb_deptnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_deptnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_deptnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_signup;
    private javax.swing.JComboBox cb_deptname;
    private javax.swing.JLabel dateofjoin;
    private com.toedter.calendar.JDateChooser dc_doj;
    private javax.swing.JLabel lbl_city;
    private javax.swing.JLabel lbl_country;
    private javax.swing.JLabel lbl_deptname;
    private javax.swing.JLabel lbl_emptype;
    private javax.swing.JLabel lbl_fname;
    private javax.swing.JLabel lbl_gender;
    private javax.swing.JLabel lbl_hno;
    private javax.swing.JLabel lbl_lname;
    private javax.swing.JLabel lbl_mname;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_state;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JRadioButton rbtn_female;
    private javax.swing.JRadioButton rbtn_male;
    private javax.swing.JRadioButton rbtn_permanent;
    private javax.swing.JRadioButton rbtn_temporary;
    private javax.swing.JTextField txt_city;
    private javax.swing.JTextField txt_country;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_hno;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_mname;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_state;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
